spring.application.name=AssignmentDemo
server.port=8080

# hr_db data source configuration
app.datasource.hr.url=jdbc:mysql://localhost:3306/hr_db
app.datasource.hr.username=root
app.datasource.hr.password=root
app.datasource.hr.driver-class-name=com.mysql.cj.jdbc.Driver

# utility_db data source configuration
app.datasource.utility.url=jdbc:mysql://localhost:3306/utility_db
app.datasource.utility.username=root
app.datasource.utility.password=root
app.datasource.utility.driver-class-name=com.mysql.cj.jdbc.Driver

